### ISSUE TITLE
Location Radius Popup

### ISSUE THREAD

**Issue by fedorgrab** [anarchyincubator/eggslist-frontend#102]
Call [locate method](https://eggslist-dev.ferialabs.com/api/docs/#users-locate-read) first before other methods. When users signs in page is supposed to be refresh. When location is changed, dynamic content is supposed to be refreshed (either partial or all). When user signs out it supposed to be refreshed as well. If you call [set location method](https://eggslist-dev.ferialabs.com/api/docs/#users-set-location-create) you need to call [locate method](https://eggslist-dev.ferialabs.com/api/docs/#users-locate-read) as user can change the lookup_radius and it should be always seen by them. 

### Main page: 
logic remains the same, just fix the refreshing.
### Catalog page:
Implement **Location PopUp** with 2 inputs:
Location city search (the same as in main page search logic: case insensetive, dash insensetive, look for states) and a lookup radius drop down (choices are: 5, 10, 20 (default), 50, 100).
PopUp is shown in 2 scenarios:
* When user wants to change current location. PopUp should have the id "set-location". PopUp should have values for city and radius from [locate method](https://eggslist-dev.ferialabs.com/api/docs/#users-locate-read). 
* When [locate method](https://eggslist-dev.ferialabs.com/api/docs/#users-locate-read) returns `is_undefined` true. Popup should have the id "set-location-undefined". Popup should show values for city and radius from [locate method](https://eggslist-dev.ferialabs.com/api/docs/#users-locate-read)
These different IDs will be used by an analytical app.

**Comment by Wazti** [comment]
done
