### ISSUE TITLE
Blogs draft

### ISSUE THREAD

**Issue by Wazti** [anarchyincubator/eggslist-frontend#110]

**Comment by fedorgrab** [comment]
LInks:
* Eggslist [API docs for blog](https://eggslist-dev.ferialabs.com/api/docs/#blogs-blogs-read)
* Summernote Wysiwyg [settings for backend](https://github.com/anarchyincubator/eggslist-backend/blob/development/app/settings/base.py#L200)
* [Summernote JS Toolbar Docs](https://summernote.org/deep-dive/#custom-toolbar-popover) to implement the same settings as in our admin app.
