### ISSUE TITLE
Use default sorting and page parameters in catalog

### ISSUE THREAD

**Issue by fedorgrab** [anarchyincubator/eggslist-frontend#26]
When user lands to catalog use page=1, ordering=... to filter the very first query.

**Comment by Wazti** [comment]
closed in [commit](https://github.com/anarchyincubator/eggslist-frontend/issues/27)

**Comment by fedorgrab** [comment]
The query param is updated, but the backend API call is still plain without the query.

**Comment by Wazti** [comment]
done
