### ISSUE TITLE
Popular Near You doesn't list 'out of stock'

### ISSUE THREAD

**Issue by wangahrah** [anarchyincubator/eggslist-frontend#49]
this item (poison mushrooms) is labelled out of stock but shows in Popular Near You
![image](https://user-images.githubusercontent.com/1247276/192161976-c5f7509d-9717-44b0-a6ce-1be18174eac7.png)
![image](https://user-images.githubusercontent.com/1247276/192161984-859f0405-e499-46ce-ac13-eceac6c7a94f.png)

**Comment by fedorgrab** [comment]
It still doesn't show status of out of stock
