### ISSUE TITLE
No favorite farmers plug

### ISSUE THREAD

**Issue by fedorgrab** [anarchyincubator/eggslist-frontend#56]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/26435815/192172199-f6681f99-c863-486f-822b-e1f769fbf8aa.png">

If the user doesn't have favorite farmers yet, they should see the same plug but with:

**Comment by wangahrah** [comment]
1. You don't have any Favorite Farmers yet
2. Add farmers to your favorites to start growing your virtual farmer's market!
3. Market
