### ISSUE TITLE
Chrome uses NAME for remember login, not email

### ISSUE THREAD

**Issue by wangahrah** [anarchyincubator/eggslist-frontend#66]
When signing up with new account, Google prompts to remember password (in chrome). It uses the NAME field instead of EMAIL field for login ( so when I let google fill in the password form, it puts Michael in the login field, not my email).

**Comment by fedorgrab** [comment]
When you create a new user you will get this:
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/26435815/192544518-77173d79-dfd0-45fd-896b-6dae5dfa9154.png">
