### ISSUE TITLE
Remove "stories" links for now

### ISSUE THREAD

**Issue by wangahrah** [anarchyincubator/eggslist-frontend#75]
Since blogs are being pushed back we can delete stories from header/footer

**Comment by fedorgrab** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/26435815/193642743-dead3a54-0967-464c-87f6-f26c651adaff.png">
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/26435815/193642776-6eeb696b-b82d-45e4-9e5f-e66c31df2bf4.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/26435815/193642917-2e8ebfc3-ada2-436e-9d66-ef79391dc918.png">


Hide these blocks as well.

**Comment by fedorgrab** [comment]
<img width="271" alt="image" src="https://user-images.githubusercontent.com/26435815/193643011-148ac6d5-2aca-4dc3-9039-b6dded85c1fb.png">
The last one is in my profile

**Comment by fedorgrab** [comment]
I found one more in mobile:
![image](https://user-images.githubusercontent.com/26435815/194566797-ec9a5fc7-a6e8-412f-9147-7f1045a32c00.png)
